RFC: add a build option to not build (executable) binaries
dankamongmen/notcurses pull request #2467
Opened 2021-12-13 11:04 UTC by KristofferC

In my use case, it is not terribly important to have all the binaries around since I just want to make a wrapper on top of the library itself. Therefore, I thought it would make some sense to have a build option that would disable building them, similar to `USE_POC`, but that also applies to the larger executables.

I was unsure if the option should be called `USE_BINARIES` or `BUILD_BINARIES`. I am also not sure if disabling `USE_POC` when `BUILD_BINARIES=off` is the correct thing to do.

2021-12-13 14:16 UTC, dankamongmen commented
i want to take a closer look at this, but you can count on it or something like it being merged today. thanks for your burst of contributions -- truly appreciated!

2021-12-13 14:41 UTC, KristofferC commented
No rush from my side :)

2021-12-14 06:34 UTC, dankamongmen commented
this looks fine. i'd ask you to add a comment to `INSTALL.md` / `README.md`, but i'll just do it. thanks!

2021-12-14 06:35 UTC, dankamongmen commented
actually i think i'd prefer `BUILD_EXECUTABLES` to `BUILD_BINARIES` just so a younger version of myself doesn't mail me and be like "shared objects are binaries you dumb piece of shit"

2021-12-14 06:39 UTC, dankamongmen commented
yeah update to `BUILD_EXECUTABLES` and this is cool to go in.

2021-12-14 06:39 UTC, dankamongmen requested changes

2021-12-14 06:39 UTC, dankamongmen commented on INSTALL.md
> +* `BUILD_BINARIES=on`: build binary (executable) targets
BUILD_EXECUTABLES if you'd please

2021-12-14 10:32 UTC, KristofferC commented
> actually i think i'd prefer BUILD_EXECUTABLES to BUILD_BINARIES just so a younger version of myself doesn't mail me and be like "shared objects are binaries you dumb piece of shit"

Agreed and updated. But it seems that the term "binary" is used in most places to talk about specifically executables. 

For example in the README: 

> Nine binaries are installed as part of Notcurses:

, where I think that "binaries" here are used to distinguish it from the libraries being built.

2021-12-14 16:45 UTC, merged